### ISSUE TITLE
mongo db bilgilerini gizleme

### ISSUE THREAD

**Issue by sevkioruc** [Buraksmn/csmm#3]
db kullanıcı adı ve parolasının environment variable şeklinde tutulması daha iyi olabilir

**Comment by Buraksmn** [comment]
@sevkioruc teşekkürler. dün yaptıgımız güncellemede

hem client hemde server tarafı için .env dosyaları eklendi.
mongodb ilk connectionString'i eski commitlerden görülebilecegi için yeni bir mongo database oluşturdum ve connectionString'i degiştirdim.
